---
project_name: authlog_exporter

builds:
  - env: 
      - CGO_ENABLED=0
    goos: 
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags: 
      - -trimpath
      - -mod=vendor
    ldflags: "-s -w -X main.version={{ .Version }}"
    main: .

archives:
  - id: authlog_exporter
    files:
      - LICENSE
    format: tar.gz
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    replacements:
      amd64: x86_64
      darwin: macos

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  draft: true

changelog:
  skip: true